iparcer/config/routes.rb
Rails.application.routes.draw do

	root 'basic#index'

	get 'basic/index'

 	get 'imports' => 'basic#imports'

	get '/importbtn', to: 'basic#importbtn', as: 'importbtn'

end

iparcer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

iparcer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

iparcer/app/controllers/basic_controller.rb
class BasicController < ApplicationController
	
	require 'open-uri'

  def index
  end

  def imports
  end

  def importbtn
		output = File.open "shops_list.txt", "r"
			while (line = output.gets) 
				IO.copy_stream(open(line.strip!.inspect), 'storage/shop1.xml')
			end
		output.close

	end
  
end

iparcer/app/helpers/application_helper.rb
module ApplicationHelper
end

iparcer/app/helpers/basic_helper.rb
module BasicHelper
end

iparcer/app/views/basic/imports.html.erb
<h1>Import catalogues</h1>
<br/>

<%= button_to "Download", importbtn_path, method: :get %>

<br/>
<br/>

<p>	Resources:</p>
<% output = File.open "shops_list.txt", "r" %>
	<ul>
		<% while (line = output.gets) %>
			<li><%= line %></li>
		<% end %>
	</ul>
<% output.close %>

iparcer/app/views/basic/index.html.erb
<h1>Main page</h1>

iparcer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iparcer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>